spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LionelOrange/config-server.git
          search-paths: config
          username: xx
          password: xx

server:
  port: 7001
